server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongo
      password: mongo
      database: springcloud
      authentication-database: admin
