version: '3'

services:
  mongodb:
    image: mongo:bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: springcloud
    ports:
    - "27017:27017"
