server:
  port: 8080

logging:
  level:
    com.learning.microservices.ecommerce.sidetrip.springcloud.productweb.service: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix.enabled: true
