server:
  port: 8080

logging:
  level:
    com.learning.microservices.ecommerce.sidetrip.springcloud.productweb.service: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 500
        readTimeout: 500
        loggerLevel: basic
  hystrix.enabled: false


hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 1000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
